### ISSUE TITLE
Add an option for lager_console_backend for output to STDERR

### ISSUE THREAD

**Issue by joedevivo** [erlang-lager/lager#168]
While this is being done, it would be a great opportunity to migrate lager_console_backend to the new style config.

**Comment by jlouis** [comment]
Some investigation:

The console backend logs via `io:put_chars(user, ...)` (see `handle_event/2` in `lager_console_backend`). You can send data to stderr by using `standard_error` in place of `user`. But more work is needed in order to make this a configurable option, notably coming up with the necessary changes to the console backend configuration line. Perhaps you would need to simply accept:

    {lager_console_backend, info, stderr}

in lieu of

    {lager_console_backend, info}

**Comment by mrallen1** [comment]
As #409 is merged and 3.5.0 released, closing this issue. Thanks!
