### ISSUE TITLE
lager not support OTP21 [erts-10.2]  on MacOS Mojave 10.14.2 by brew install erlang?  

### ISSUE THREAD

**Issue by vzzy** [erlang-lager/lager#487]
{erl_opts, [
	debug_info,
	{parse_transform, lager_transform},
]}.
{deps, [
	{lager, ".*", {git, "https://github.com/erlang-lager/lager.git", {branch,"master"}}},

Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:30] [hipe] [dtrace]

Eshell V10.2  (abort with ^G)
(im1@127.0.0.1)1> application:start(lager, permanent).
{error,{already_started,lager}}
(im1@127.0.0.1)2> lager:error("hello world").
** exception error: undefined function lager:error/1

Why me get this exception ?

**Comment by vzzy** [comment]
I  use lager sample config below : 

{lager, [
  	{log_root, "../logs"},
  	{handlers, [
	    {lager_console_backend, [{level, info}]},
	    {lager_file_backend, [{file, "error.log"}, {level, error}]},
	    {lager_file_backend, [{file, "console.log"}, {level, info}]}
	]}
  ]}

**Comment by mrallen1** [comment]
Hi. You can't call `lager:error` from the Erlang REPL - it exists only as a "virtual" function in your code. Lager's parse transform turns the `error` function into the "real" function that does all of the work at compile time. Since the REPL doesn't use or even understand parse transformations, this function call will always say that its undefined.

**Comment by vzzy** [comment]
Thank you.  It's my fault,sorry.

**Comment by mrallen1** [comment]
No worries. It's easy to get confused about this.
